### ISSUE TITLE
Use with QSPlashscreen

### ISSUE THREAD

**Issue by BrnSlr** [antonypro/QGoodWindow#10]
On Win10, with Qt5.15.2, the use of QGW with a QSplashcreen is not possible and the application crashes.

With the GoodShowCase example

`QPixmap pixmap(":/splash.png");`
`QSplashScreen splash(pixmap);`
`splash.show();`
`MainWindow *mw = new MainWindow();`
`mw->show();`
`splash.finish(mw);`

**Comment by antonypro** [comment]
@BrnSlr: Sorry for the late response.

I reproduced the problem and confirmed that is a bug, I'm working on a solution and the next version of `QGoodWindow` will contain the solution.

Please wait the next release. Thanks!

**Comment by antonypro** [comment]
This issue has been fixed in version 2.0. 

I'll close this issue for now, but if you believe it's not really solved, please inform me so i can reopen the issue.
