### ISSUE TITLE
[Suggestion] Optional menu bar that's incorporated into the title bar

### ISSUE THREAD

**Issue by despawnedd** [antonypro/QGoodWindow#16]
I'm suggesting the ability to use a menu bar that's incorporated into the title bar, like in Visual Studio Code:

![Visual Studio Code example](https://s33046.pcdn.co/wp-content/uploads/2020/07/command-palette-1.png)

By the way, great job with this library! Can't wait to try it out for myself.

**Comment by despawnedd** [comment]
My bad, didn't realize a title bar doesn't come with the library itself. Closing.

**Comment by antonypro** [comment]
@despawnedd: Just to note, it's actually possible put a QMenuBar inside the title bar widget, add left margin for it and use style sheets to customize the menu appearance.

Thanks!

**Comment by despawnedd** [comment]
Alright, thank you.

Here's another question (I don't want to open another issue for this): if I wanted to add a button in the ExampleMinimal's title bar that would, for example, maximize the window, how would I do that?
I'm sorry for asking such a basic thing, but I can't figure out how to place a widget into the title bar area. I've tried putting a button that's in the MainWindow _itself_, and then setting the margins of the title bar thinking it'd let the click event through, but that didn't work.
Thanks in advance.

**Comment by despawnedd** [comment]
@antonypro Sorry for mentioning You, but I'm kind of stuck here. Just want to add a widget to the base title bar.

**Comment by antonypro** [comment]
@despawnedd: The simpler way to put `QWidget` as title bar caption buttons is using layouts to put the child widget of central widget on the top right corner and use the API `setMargins` to ensure that area could be clicked and not used to move the window.

However you can put any kind of widget as central widget, and handle the click events on the corner that contains the caption buttons.

You are also able to let the `QGoodWindow` handle the caption buttons and repaint the buttons accordingly with the state passed through `captionButtonStateChanged` `SIGNAL`, but this is only needed to show the tile menu on Windows 11 when maximize button is hovered.

Here goes a very simple example:

_mainwindow.h:_

```
#include <QGoodWindow>

class MainWindow : public QGoodWindow
{
    Q_OBJECT
public:
    MainWindow(QWidget *parent = nullptr);
    ~MainWindow();

private slots:
    void styleWindow();

private:
    //Functions
    bool event(QEvent *event);

    //Variables
    QWidget *m_caption_buttons_widget;
    QWidget *m_title_bar_widget;
    QWidget *m_central_widget;
    QPushButton *m_button_minimize;
    QPushButton *m_button_maximize;
    QPushButton *m_button_restore;
    QPushButton *m_button_close;
};
```

_mainwindow.cpp:_

```
#include "mainwindow.h"

MainWindow::MainWindow(QWidget *parent) : QGoodWindow(parent)
{
    m_button_minimize = new QPushButton("Minimize", this);
    m_button_maximize = new QPushButton("Maximize", this);
    m_button_restore = new QPushButton("Restore", this);
    m_button_close = new QPushButton("Close", this);

    connect(m_button_minimize, &QPushButton::clicked, this, &QGoodWindow::showMinimized);
    connect(m_button_maximize, &QPushButton::clicked, this, &QGoodWindow::showMaximized);
    connect(m_button_restore, &QPushButton::clicked, this, &QGoodWindow::showNormal);
    connect(m_button_close, &QPushButton::clicked, this, &QGoodWindow::close);

    m_caption_buttons_widget = new QWidget(this);

    QHBoxLayout *caption_buttons_layout = new QHBoxLayout(m_caption_buttons_widget);
    caption_buttons_layout->setContentsMargins(0, 0, 0, 0);
    caption_buttons_layout->setSpacing(0);
    caption_buttons_layout->addWidget(m_button_minimize);
    caption_buttons_layout->addWidget(m_button_maximize);
    caption_buttons_layout->addWidget(m_button_restore);
    caption_buttons_layout->addWidget(m_button_close);

    m_title_bar_widget = new QWidget(this);

    QHBoxLayout *title_bar_layout = new QHBoxLayout(m_title_bar_widget);
    title_bar_layout->setContentsMargins(0, 0, 0, 0);
    title_bar_layout->setSpacing(0);
    title_bar_layout->addStretch();
    title_bar_layout->addWidget(m_caption_buttons_widget);

    m_central_widget = new QWidget(this);

    QVBoxLayout *central_layout = new QVBoxLayout(m_central_widget);
    central_layout->setContentsMargins(0, 0, 0, 0);
    central_layout->setSpacing(0);
    central_layout->addWidget(m_title_bar_widget);
    central_layout->addStretch();

    setCentralWidget(m_central_widget);
}

MainWindow::~MainWindow()
{

}

void MainWindow::styleWindow()
{
    setMargins(m_title_bar_widget->height()/*Title bar height*/,
               0/*Icon size*/,
               0/*Left margin*/,
               m_caption_buttons_widget->width()/*Right margin*/);

    bool maximized = isMaximized();

    m_button_maximize->setVisible(!maximized);
    m_button_maximize->setEnabled(!maximized);

    m_button_restore->setVisible(maximized);
    m_button_restore->setEnabled(maximized);
}

bool MainWindow::event(QEvent *event)
{
    switch (event->type())
    {
    case QEvent::Show:
    case QEvent::WindowActivate:
    case QEvent::WindowDeactivate:
    case QEvent::WindowStateChange:
    {
        styleWindow();
        break;
    }
    default:
        break;
    }

    return QGoodWindow::event(event);
}
```

**Comment by despawnedd** [comment]
Thank You! This is really simple and it works! No idea why my previous attempt didn't work, though.

**Comment by despawnedd** [comment]
@antonypro Just one more question (and then I'll hopefully finally stop with this, sorry for bothering You by the way):

How did You make the icon widget in GoodShowCase open the native window actions context menu when clicked?
![image](https://user-images.githubusercontent.com/50424428/188663127-47b49db3-f6ea-432b-bf6d-2afea5dbaceb.png)

EDIT: Never mind, figured it out! I've gotta set the left margin to enable this.

**Comment by sunnyorrainy** [comment]
How to put a QMenuBar inside the title bar widget? can you show me an example?

**Comment by despawnedd** [comment]
@sunnyorrainy Just put a QMenuBar in whatever layout you're using for the title bar. I'll try to make an example this weekend.

**Comment by sunnyorrainy** [comment]
I learned how to do that from https://github.com/despawnedd/SimpleTextEditor/tree/main/SimpleTextEditor.  Thank you!

**Comment by despawnedd** [comment]
Oh, alright! I'm really glad to see my code helped someone!

**Comment by antonypro** [comment]
@sunnyorrainy: The next version will include an example of menu bar at the title bar, among other features.

But, for now, I'm glad that you found your solution.
