### ISSUE TITLE
Left margin of title bar treats everything as an icon

### ISSUE THREAD

**Issue by despawnedd** [antonypro/QGoodWindow#17]
_(continuation of issue #16 )_

Okay, so, I've managed to add a QMenuBar to the title bar and set the left margin for it.

![image](https://user-images.githubusercontent.com/50424428/188683340-9ca4017f-444a-4832-a56e-5b99de2891ab.png)

The issue is - the left margin treats everything as an icon and I can't click on the menu bar. Notice how double clicking that area also closes the window, as if I double clicked an actual icon.

https://user-images.githubusercontent.com/50424428/188686147-03cfc19e-5d4b-4b7c-8761-60c9a1bb5733.mp4

Here's an example without the small icon next to it.

https://user-images.githubusercontent.com/50424428/188686035-0ed1e76b-135c-4c70-848a-fb617a02dd25.mp4

A potential solution would be to have two left margins: one for the actual icon, and another to let clicks through.

**Comment by antonypro** [comment]
@despawnedd: Hi, please note that actually the `setMargins` API allows you custom icon width, and, left margin.

So i think you just need to set in pixels the icon width, and the left margin that only covers width of left widget, not counting the icon width.

So if you have a icon with width 30 and a left widget with width 100, use:

```
setMargins(/*set title bar height*/, 30, 100, /*set right margin*/);
```

**Comment by despawnedd** [comment]
Oh, okay. Thank You for the response. Will try to look into the API more before making issues like this in the future.
