### ISSUE TITLE
Add CMake files alongside QMake files

### ISSUE THREAD

**Issue by russellbanks** [antonypro/QGoodWindow#18]
To use this library in a CMake project, I had to rewrite the pro/pri files into CMakeLists.txt (I used [qmake2cmake](https://www.qt.io/blog/introducing-qmake2cmake) by Qt to achieve this). It would be nice to have both so that this can be used in either build system.

**Comment by antonypro** [comment]
@russellbanks: In the past i provided support for both qmake and Qbs and i realized that is really easy make a mistake when editing and trying to keep in sync multiple build systems, for Qt 5 and Qt 6, on Windows, Linux macOS and the cases when the library has no use, for example Android.

I'm not saying no to CMake, what i'm saying is if support for CMake is added, it will delay even more each new version release.

I can't say if CMake will be added or not for now.

**Comment by antonypro** [comment]
CMake build system was added in version 2.1.
