### ISSUE TITLE
[Qt 6] QGoodWindow breaks on Windows with scaling values different from 100%

### ISSUE THREAD

**Issue by kresimirko** [antonypro/QGoodWindow#19]
### QGoodWindow breaks on Windows with scaling values different from 100%, as seen below:

![image](https://user-images.githubusercontent.com/104278083/209578732-b21d7978-81e6-4942-9ecf-c3ce7c0c3643.png)
_Scaling 100%, QGoodWindow is present_

---

![image](https://user-images.githubusercontent.com/104278083/209578803-75d2d71a-0d4f-4b3e-88bd-4a9baf4c073f.png)
_Scaling 100%, QGoodWindow is bypassed_

---

![image](https://user-images.githubusercontent.com/104278083/209578947-5d01c0b9-2c79-42c3-a1cb-1c03bc821009.png)
_Scaling 125%, QGoodWindow is present_

---

![image](https://user-images.githubusercontent.com/104278083/209578884-71066f8f-dde6-4609-aa4a-12c3f00320de.png)
_Scaling 125%, QGoodWindow is bypassed_

Another thing I noticed is that the QGoodWindow shadow on Windows 10 also behaves weirdly. I might send a video demonstrating this later.

Source code for this is here (EDIT: removed the link since it was unnecessary) (run with `-q` as an argument to bypass QGoodWindow).

**Comment by kresimirko** [comment]
Checked if this occurs with GoodShowCase. It seems to work fine (although the title bar doesn't increase in size). Strange, I can't find anything in the code that could be causing this (at least not yet).

**Comment by kresimirko** [comment]
I'll just try to use GoodShowCase's code, essentially replacing the main window contents of it with mine. (I'll keep the copyright notice and the license, of course)

Still curious about what exactly is causing this.

**Comment by kresimirko** [comment]
ExampleMinimal seems to exhibit the same behavior (not working properly)
![image](https://user-images.githubusercontent.com/104278083/209677598-8786df13-a771-46e7-acd9-88d9a7e56170.png)
Here's the shadow issue as I mentioned.

**Comment by kresimirko** [comment]
After some tinkering, I found out that the GoodShowCase build I had that "worked" didn't scale all elements. After rebuilding with Qt 5.15.2 I got the same result. With Qt 6.4.1 the window exhibits the same issue as in the images above, however the scaling is more consistent. (see both below)

![image](https://user-images.githubusercontent.com/104278083/209687813-5a560fcf-857b-4632-b6ba-3b3a61a824a1.png)
Here's a comparison between the Qt 6.4.1 build and the Qt 5.15.2 build (125% scaling)

---

![image](https://user-images.githubusercontent.com/104278083/209687631-a3399178-58a3-4599-9dbb-98d7ecc44280.png)
Here's the same comparison, this time the scaling is 100%

**Comment by antonypro** [comment]
@kresimirko: Hi! The problem, as you noted, is automatic scaling in Qt 6.

The solution, if you plan to develop only for Qt 6 is put…

	qputenv("QT_ENABLE_HIGHDPI_SCALING", "0");

...before `QApplication a(argc, argv);`. This disables the automatic scaling of Qt 6, and force the app to behaves like in Qt 5.

If you could, please confirm this for me or point that this is not the solution.

If this solves the problem, I will include a more elegant solution to the problem on next version.

Thanks!

**Comment by kresimirko** [comment]
Just tried that and, yes, it does prevent the app from scaling.

![image](https://user-images.githubusercontent.com/104278083/209696548-1c5607e1-0616-4975-92a6-3c6ce240b9aa.png)

Just asking, will a future QGoodWindow version be compatible with automatic scaling (if that's what You meant by a "more elegant solution")?

**Comment by antonypro** [comment]
@kresimirko: For the next immediate version, I’m planning to only add to QGoodWindow a static function that calls `qputenv("QT_ENABLE_HIGHDPI_SCALING", "0");` only on Qt 6, in Qt 5 it will do nothing. No change in the scale behavior planned for now.

**Comment by kresimirko** [comment]
Okay. Thanks for answering.

**Comment by antonypro** [comment]
The static function `QGoodWindow::setup();` was added in version 2.1 and should be called before `QApplication`.
