### ISSUE TITLE
Is there any plan to support Qt's scaling strategy?

### ISSUE THREAD

**Issue by jxiaow** [antonypro/QGoodWindow#25]
Is there any plan to support Qt's scaling strategy?

`QGuiApplication::setAttribute(Qt::AA_EnableHighDpiScaling); `
  `QGuiApplication::setAttribute(Qt::AA_UseHighDpiPixmaps);`
  `QGuiApplication::setHighDpiScaleFactorRoundingPolicy(Qt::HighDpiScaleFactorRoundingPolicy::PassThrough);`

**Comment by kresimirko** [comment]
I can't be the one to say anything, but the author did say this: https://github.com/antonypro/QGoodWindow/issues/19#issuecomment-1366054300

**Comment by jxiaow** [comment]
Because most applications now need to adapt to 2k or 4k high-definition screens, but I read the author's reply and the zoom function of Qt is turned off by default

**Comment by jxiaow** [comment]
I hope to support or provide some ideas, thanks @antonypro

**Comment by Renleilei1992** [comment]
high dpi support is indeed necessary,  but it's a terrible work to adapt it.

**Comment by antonypro** [comment]
@jxiaow, @kresimirko  and @Renleilei1992:

Due to demand I'm going to start attempts to support automatic scaling, it's really hard, but i will notice you when it goes to be implemented or if the idea is abandoned.

Thanks all!

**Comment by jxiaow** [comment]
@antonypro thanks, i will look forward to your notification。

**Comment by antonypro** [comment]
@jxiaow, @kresimirko and @Renleilei1992: This feature was added on version 2.3.

**Comment by antonypro** [comment]
I believe the issue is resolved, so I am closing this issue.
