### ISSUE TITLE
Importing QGW as a shared library yields a linker error

### ISSUE THREAD

**Issue by kresimirko** [antonypro/QGoodWindow#26]
I've built QGoodWindow as a shared library using `qgoodwindow-shared-lib.pro`.

I got this as a result:

![image](https://user-images.githubusercontent.com/104278083/216171944-9412efc7-aea8-4b00-b1f0-7dc40c6c592a.png)

I then put that in a folder and linked to that using QMake:

```qmake
unix|win32: LIBS += -L$$PWD/../deps/QGoodWindow/ -lQGoodWindow

INCLUDEPATH += $$PWD/../deps/QGoodWindow
DEPENDPATH += $$PWD/../deps/QGoodWindow
```

...with the folder's content looking like this:

![image](https://user-images.githubusercontent.com/104278083/216172729-a5c1becd-6ff1-4aea-a5fe-4f4c58479f25.png)

Everything went fine, until I got this error while trying to build my application:

```
moc_mainwindow.obj:-1: error: LNK2019: unresolved external symbol "public: static struct QMetaObject const QGoodWindow::staticMetaObject" (?staticMetaObject@QGoodWindow@@2UQMetaObject@@B) referenced in function "public: static struct QMetaObject const * __cdecl QMetaObject::staticMetaObject<&public: static struct QMetaObject const QGoodWindow::staticMetaObject>(void)" (??$staticMetaObject@$1?staticMetaObject@QGoodWindow@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ)
```

I've tried rebuilding (my application and not the library) and other things to no avail.

**Comment by antonypro** [comment]
@kresimirko: You need to use some `DEFINES` to use the library:

- You need to define `QGOODWINDOW`.
- If building with QGoodCentralWidget you need to define `QGOODCENTRALWIDGET`.
- If building as shared library you need to define `WITH_LIBRARY`.
- If using with Qt 5 you need to define `QT_VERSION_QT5`.
- If using with Qt 6 you need to define `QT_VERSION_QT6`.

Example with QMake:

	DEFINES += QGOODWINDOW  #QGoodWindow macro
	DEFINES += QGOODCENTRALWIDGET #If compiled the library with QGoodCentralWidget
	DEFINES += WITH_LIBRARY #If using library as shared library

	equals(QT_MAJOR_VERSION, 5){
	DEFINES += QT_VERSION_QT5
	}
	equals(QT_MAJOR_VERSION, 6) {
	DEFINES += QT_VERSION_QT6
	}

Or compile the CMake version because they uses proper headers that automatically defines these macros.

I will document it better in the future.

Thanks!

**Comment by kresimirko** [comment]
This worked, thank you so much!

**Comment by antonypro** [comment]
@kresimirko: Please note that these defines are not needed on version 2.3.

**Comment by kresimirko** [comment]
@antonypro I've tried using 2.3 just now and this error pops up again, no matter if I have the defines in my .pro file. May You please provide a guide on properly including and using QGoodWindow as a shared library? Thanks in advance.

**Comment by antonypro** [comment]
@kresimirko: You have to use the include folder produced on `make install` if using `CMake` or the include folder produced when building with `QMake`.

I planning to add this information to the docs.

Can you please confirm if the solution works or if there is any problem remaining?

**Comment by kresimirko** [comment]
@antonypro

![image](https://user-images.githubusercontent.com/104278083/219768765-6ed5ed64-297e-4481-9d52-e1ff2a6694c2.png)

I'm not sure how to include this, as the src folder does not exist in the final result. Do I have to copy/move the src folder from the root QGoodWindow folder or do something else?

**Comment by antonypro** [comment]
@kresimirko: It can be found on `..path_to\QGoodWindow\build-library\build\build-shared\include` if building `QGoodWindow` only, with `QMake`.

**Comment by kresimirko** [comment]
@antonypro The path in the image is the same as the path You just mentioned; maybe I built something incorrectly or maybe this is a bug...?

**Comment by kresimirko** [comment]
It appears I had done something wrong, and the folder seems to have been made correctly now. Will try including this. Sorry for the false alarm.
