### ISSUE TITLE
[Enhancement request] Minimization does not work as expected

### ISSUE THREAD

**Issue by kresimirko** [antonypro/QGoodWindow#28]
Hello again. I'm back another with another issue; this time it's not really a bug, rather a request for an enhancement.

When using `showMinimized();`, the window does get minimized, however it doesn't lose focus (somehow) and remains selected in the taskbar and other places:

![image](https://user-images.githubusercontent.com/104278083/216442665-8cf12f43-4fc5-4c4b-bed3-f55cc10e9e6b.png)

The behavior I expected is the previous active window regaining focus. 

Tested this out on GoodShowCase too.

_(I'm sorry for creating so many issues... I'm trying to properly learn how to use the library and help its development as much as I can.)_

**Comment by antonypro** [comment]
@kresimirko: This enhancement will be addressed in next version.

**Comment by antonypro** [comment]
@kresimirko: This enhancement was addressed on version 2.3.
