### ISSUE TITLE
[Question]Why is testAttribute called twice

### ISSUE THREAD

**Issue by bulaia** [antonypro/QGoodWindow#29]
I'm learning about this great open source library, but I don't understand what it means here.

https://github.com/antonypro/QGoodWindow/blob/d0a17a62ef81a08a28d929e07bfce3e1444674a0/QGoodWindow/QGoodCentralWidget/src/qgoodcentralwidget.cpp#L565-L581

This place has been judged twice
`if (!widget->mask().isNull() ||  widget->testAttribute(Qt::WA_TransparentForMouseEvents)) `
and
`if (!widget->mask().isNull() &&  !widget->testAttribute(Qt::WA_TransparentForMouseEvents)) `

Looking forward for your reply, thank you.

**Comment by antonypro** [comment]
@bulaia: The twice check is not necessary, it will be fixed in next version.

Thanks for reporting!

**Comment by antonypro** [comment]
@bulaia: This bug was solved on version 2.3.
