### ISSUE TITLE
winextras module was removed in qt 6

### ISSUE THREAD

**Issue by Guto-tw14** [antonypro/QGoodWindow#3]
![image](https://user-images.githubusercontent.com/54808180/126046161-226bdf2e-8771-4959-926f-942198023095.png)

**Comment by Guto-tw14** [comment]
https://doc-snapshots.qt.io/qt6-dev/whatsnew60.html#removed-modules-in-qt-6-0

**Comment by antonypro** [comment]
@wooow55: The removal of `x11extras` module on Linux and `winextras` module on Windows breaks the compatibility of this library with Qt 6.

Hopefully, in a future version of Qt 6, these modules may be reinstated and `QGoodWindow` be ported to Qt 6.
