### ISSUE TITLE
QSystemTray Menu size is not sync with scaling

### ISSUE THREAD

**Issue by sorudals** [antonypro/QGoodWindow#34]
Hello, I really appreciate your work. 

I have a problem about scale factor of QMenu of QSystemTrayIcon.

Whenever I change scaling of display, size of QMenu of QSystemTrayIcon is not changed. 

I want to know how to fit the scale of qmenu size.

**Comment by antonypro** [comment]
@Skm1221: Hi! Firstly, sorry for the reply time.

`QGoodWindow` does not manage scale dynamically at run-time, you must close the app and open it again to "re-scale" the app, and add dynamic change is not planned for now.

Thanks!

**Comment by sorudals** [comment]
Thank you for reply!!! 

Um... Then do you have any idea or keyword to solve dynamic resolution changing situation??

**Comment by antonypro** [comment]
@Skm1221: Due to demand, I'm starting tests of dynamic window scale as `QMainWindow` does. However, if it will be implemented depends on the success of my attempts.

Thanks!

**Comment by antonypro** [comment]
@Skm1221: Could you please tell if the problem happens with version 2.4?

**Comment by sorudals** [comment]
@antonypro: I tested it, and the problem was solved! Thanks.

However, I encountered another issue in my project where I utilize QML components. When I change the display scale from 100% to 200%, the size of the MainWindow is increased more than double.

Perhaps in version 2.3, the sizes of both the MainWindow and the QML components are not changed, preventing this problem from occurring.

How can I modify the MainWindow to address this issue?

I added screenshots for better understanding. 



----------------------------------------------------------------------------------------------------------------------
###  Start Program (Display Scale 100%) and Change Display Scale to 150%


**Start - Display Scale 100% case.**
![image](https://github.com/antonypro/QGoodWindow/assets/12227644/1887e8e3-c1f5-4e70-9805-dcf65aca8444)


**Change DisplayScale -  Display Scale 150% case**
<img width="1263" alt="image" src="https://github.com/antonypro/QGoodWindow/assets/12227644/41432563-125f-4820-9a39-4c116d70b884"> 




----------------------------------------------------------------------------------------------------------------------
###  Start Program (Display Scale 200%) and Change Display Scale to 100%



**Start - Display Scale 200% case**
![image](https://github.com/antonypro/QGoodWindow/assets/12227644/b09ea42b-4c84-44ed-a8ca-18d41a9a02a1)

**Change DisplayScale - DisplayScale 100% case**
![image](https://github.com/antonypro/QGoodWindow/assets/12227644/a5e9f45a-47d1-4eb0-a234-9b7f2564269b)

**Comment by antonypro** [comment]
@Skm1221: Thanks for report, I'm working to solve these problems!

**Comment by antonypro** [comment]
@Skm1221: Could you please try version 2.4.1?

**Comment by sorudals** [comment]
@antonypro  Hi,  I really appreciate about your support!

I tried with version 2.4.1. 

It wat not solved. 
My test configuration was 

```
Resolution : 1920 x 1080
Scale : 100%
My application window size : 720 x 480
```

I tested 3 scenario.

### - First scenario

Run application > Change scale to 175% > Change scale to 100% > Change scale to 175% > Change scale to 100%
In this case, problem occured from first changing scale.

1. Run Application
![image](https://github.com/antonypro/QGoodWindow/assets/12227644/3acf0f20-a6eb-4c06-8fd7-44dfc181e947)

2. Change Scale to 175%
![image](https://github.com/antonypro/QGoodWindow/assets/12227644/660b33cb-6596-4b9a-8b76-2bb4f2b1c91a)

3. Change scale to 100% 
![image](https://github.com/antonypro/QGoodWindow/assets/12227644/d78599ec-0f17-47d3-a9f8-23284a6aa327)

4. Change Scale to 175%
![image](https://github.com/antonypro/QGoodWindow/assets/12227644/c8f9b665-b716-42c5-87c3-7ade4d2c69a8)

5. Change scale to 100% 
![image](https://github.com/antonypro/QGoodWindow/assets/12227644/3986f209-e85c-4175-845d-838d729d967a)


### - Second scenario

Run application > Change scale to 150% > Change scale to 100% > Change scale to 150% > Change scale to 100%
In this case, problem occured from second changing scale to 150%.

1. Run Application
![image](https://github.com/antonypro/QGoodWindow/assets/12227644/4840fc58-2bf3-4b25-a164-689ea4df5871)

2. Change Scale to 150%
<img width="960" alt="image" src="https://github.com/antonypro/QGoodWindow/assets/12227644/8cea3a4c-0514-493f-9d75-3cf1cc3acf77">

3. Change scale to 100% 
![image](https://github.com/antonypro/QGoodWindow/assets/12227644/82f09a12-e552-4539-b5f7-33bd97745a7b)

4. Change Scale to 150%
<img width="960" alt="image" src="https://github.com/antonypro/QGoodWindow/assets/12227644/3e0e4f5e-3178-4ffd-a21d-972b744a4f21">

5. Change scale to 100% 
![image](https://github.com/antonypro/QGoodWindow/assets/12227644/9d4261c4-4909-45f7-a508-fe0cd8bec530)

### - Third scenario

Run application > Change scale to 150% > Change scale to 125%
In this case, problem occured from changing scale to 125%.

1. Run Application
![image](https://github.com/antonypro/QGoodWindow/assets/12227644/4840fc58-2bf3-4b25-a164-689ea4df5871)

2. Change Scale to 150%
<img width="960" alt="image" src="https://github.com/antonypro/QGoodWindow/assets/12227644/8cea3a4c-0514-493f-9d75-3cf1cc3acf77">

3. Change scale to 125% 
![image](https://github.com/antonypro/QGoodWindow/assets/12227644/fa1777fe-a963-4f7e-ae88-97691de229f2)

I hope that these informations are useful to help this issue.

**Comment by antonypro** [comment]
@Skm1221: Hi! I think that i solved the problem, however I'm asking you to test what may be the 2.4.2 version:

https://github.com/antonypro/QGoodWindow/tree/test/QGoodWindow-test2

The change that matters is remove the following line:

https://github.com/antonypro/QGoodWindow/blob/d47ceddd3cad7eae67c6f7c19b7a708ed5b37cbb/QGoodWindow/QGoodWindow/src/qgoodwindow.cpp#L3065

That prevents the window for being resized twice.

I'm waiting your feedback!

Thanks!

**Comment by sorudals** [comment]
@antonypro  Hi! 
I tested with QGoodWindow-test2 and It worked perfectly!
I really appreciate your support!

**Comment by antonypro** [comment]
@Skm1221: Thanks for your appreciation of my work!

And thanks for become my first sponsor!
You've turned my hobby into a job, MANY THANKS!

The release of the next version on `master` branch depends on resolve the other open issues.

Thanks, again!

**Comment by antonypro** [comment]
I will close this issue as it seems to be solved!
