### ISSUE TITLE
CaptionButton Hover Area Offset

### ISSUE THREAD

**Issue by galvinhoang** [antonypro/QGoodWindow#35]
While playing around with the CaptionButtons and implementing a solution with them including the QSVGWidgets, I found that there is a slight offset of the area that activates hover event as seen in the photo
![grafik](https://github.com/antonypro/QGoodWindow/assets/65485156/46f2661f-211f-45fa-af75-5f1ac1aceea4)
This offset increases the more the scaling factor in Windows increases (maybe it is also affected by monitor size? I use 1440p but not sure about that...)
I digged in the code but so far I was unable to find, where this hover area is even coming from because to me it does not seem to be coming from within the CaptionButton class itself.

(the foto was taken at 225% scaling, I know noone should use such a large scaling factor but this issue also seems to be slightly present at 100% for me.
Note that I did change the width of the CaptionButtons to 36, but for me this issue was also present for the default width.)

**Comment by antonypro** [comment]
@galvinhoang: Thanks for reporting!

In the next version a more accurate title bar mouse hit test will be present.

**Comment by sorudals** [comment]
Hi @antonypro 
When will next version release?

**Comment by antonypro** [comment]
@Skm1221: If everything goes as expected, in less than a week.

**Comment by antonypro** [comment]
@galvinhoang and @Skm1221: This bug was solved on version 2.4.
