### ISSUE TITLE
Black background during resizing

### ISSUE THREAD

**Issue by galvinhoang** [antonypro/QGoodWindow#38]
Thanks for the new update! Unfortunately, for me the Window resizing performance got a little worse. Furthermore I now have these black background edges when resizing, plus the widgets in the Window "jiggle around" which was not the case in the previous version. Is there any way to revert this?

https://github.com/antonypro/QGoodWindow/assets/65485156/429cb45a-f0a8-4ccf-b79b-a4a3bf58e1e1

**Comment by antonypro** [comment]
@galvinhoang: Thanks for report, I'm working to solve this problem!

**Comment by zavinator** [comment]
It is also obvious when running the OpenGL example - GoodShowCaseGL, that the refreshing for v2.4 is worse then in v2.3.
