### ISSUE TITLE
Dock widgets in QGoodWindow

### ISSUE THREAD

**Issue by brandonchui** [antonypro/QGoodWindow#39]
I am trying to add a dockable widget to the left of my current window using `QGoodWindow`.
```
QGoodWindow mainWindow;
QGoodCentralWidget* gCentralWidget = new QGoodCentralWidget(&mainWindow);

QWidget* widget= new QWidget();
gCentralWidget->setCentralWidget(widget);
```

When I try to set a dock widget
```
Outliner* outliner = new Outliner();
QDockWidget* outlinerDock = new QDockWidget("Outliner");
outlinerDock->setWidget(outliner);
mainWindow.addDockWidget(Qt::LeftDockWidgetArea, outlinerDock);
```
I want the dockable widget to be under title bar, but the dockable widget seems to be moving the titlebar. The minimize buttons are all are also in wrong area now, I assume because of the title bar shifting.
![image](https://github.com/antonypro/QGoodWindow/assets/7586563/31e1dc9d-3b43-46db-8071-6110644acfc4)

**Comment by antonypro** [comment]
@brandonchui: You need to add a secondary `QMainWindow` as central widget of `QGoodCentralWidget`, and add to that widget the dock widget.

Example:
Note: Here I've replaced the `outliner` widget with a empty `QPushButton`.

```
#include <QGoodWindow>
#include <QGoodCentralWidget>

int main(int argc, char *argv[])
{
    QGoodWindow::setup();

    QApplication app(argc, argv);

    QGoodWindow mainWindow;
    QGoodCentralWidget gCentralWidget(&mainWindow);

    QMainWindow mwWidget(&gCentralWidget, Qt::Widget);
    gCentralWidget.setCentralWidget(&mwWidget);

    mainWindow.setCentralWidget(&gCentralWidget);

    QPushButton* outliner = new QPushButton();
    QDockWidget* outlinerDock = new QDockWidget("Outliner");
    outlinerDock->setWidget(outliner);
    mwWidget.addDockWidget(Qt::LeftDockWidgetArea, outlinerDock);

    mainWindow.show();

    return app.exec();
}
```

**Comment by antonypro** [comment]
I'm closing this issue because it's answered.
