### ISSUE TITLE
Press F only toggle on main monitor.

### ISSUE THREAD

**Issue by hcaihao** [antonypro/QGoodWindow#4]
When window on secondary monitor.

**Comment by antonypro** [comment]
@hcaihao: Hi! Actually **QGoodWindow** doesn't support multiple screens very well.

However, in next version, i will include better multi-screen support!

Thank you for your issue report!

**Comment by hcaihao** [comment]
Great! When will next version release?

**Comment by antonypro** [comment]
@hcaihao: I'm making some improvements on the library beyond your request, that is why it may take some time!

Hopefully in less than one month i will have all prepared, acceptable tested, and released.

Thank you for your feedback!

**Comment by hcaihao** [comment]
Wait in hope, Thank you!

**Comment by antonypro** [comment]
@hcaihao: This issue was fixed on version 1.1.

Feel free to close this issue if you think it's solved, or report a possible related problem.

Thank you for report!

**Comment by antonypro** [comment]
Closing due inactivity.

**Comment by hcaihao** [comment]
Thank you, it works!
