### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by hirseboy** [antonypro/QGoodWindow#42]
If I add the pri in my project and all files are correctly included in QtCreator project, I still get "File not found" when I add "#include <QGoodWindow>"

Seems like stupid question, but I just do not find why it is not working. :(

**Comment by antonypro** [comment]
@hirseboy:

If you are including the sources, using `QMake` as build system, and using both `QGoodWindow` and `QGoodCentralWidget`, you should add to your `.pro`:

```
include(..path_to/QGoodWindow/QGoodWindow.pri)
include(..path_to/QGoodCentralWidget/QGoodCentralWidget.pri)
```

Where `..path_to` is the relative or absolute path to these files.
Please note that the order matters.

And finally include `QGoodWindow` and `QGoodCentralWidget` in your code:

```
#include <QGoodWindow>
#include <QGoodCentralWidget>
```

If you are not using `QGoodCentralWidget` use only the `QGoodWindow` includes.

I hope that helps you!

**Comment by antonypro** [comment]
I will close this issue due to inactivity.

Please tell if you think it needs to be reopened.
