### ISSUE TITLE
A dialog with QGoodWindow as the parent window will have problems.

### ISSUE THREAD

**Issue by biubiuKill** [antonypro/QGoodWindow#48]
```
MainWindow::MainWindow(QWidget *parent) : QGoodWindow(parent)
{
    QPushButton *btn = new QPushButton("test", this);
    btn->setMaximumSize(120, 40);
    connect(btn, &QPushButton::clicked, this, [this](){
        QDialog log(this);
        QVBoxLayout *out = new QVBoxLayout(&log);
        auto *sd = new QLabel("Test", &log);
        out->addWidget(sd);
        log.exec();
    });

    setCentralWidget(btn);
}
```

When I click the button, the dialog automatically stretches and an error is reported.

**Comment by biubiuKill** [comment]
Qt version 6.5.3

**Comment by biubiuKill** [comment]
Oh, sorry, this problem has been submitted.

**Comment by biubiuKill** [comment]
**But I found one problem that wasn't fixed.**


![1](https://github.com/antonypro/QGoodWindow/assets/70552008/8569b727-1279-4651-b5fe-d88c8d6fddfc)

https://github.com/antonypro/QGoodWindow/issues/47#issuecomment-1809692572

**Comment by antonypro** [comment]
Hi, @biubiuKill!

In fact the problem exists and must be already solved, but it doesn't.

To solve the problem I removed the following line from source code on version [2.4.3 beta 1](https://github.com/antonypro/QGoodWindow/tree/test/QGoodWindow-2.4.3-beta1):

https://github.com/antonypro/QGoodWindow/blob/3456aea468504576eadaa5a03402d235eea1ee5f/QGoodWindow/QGoodWindow/src/qgoodwindow.cpp#L1759

I think this solves the problem and the size set will be respected.

If you could, please give a feedback.

Thanks for reporting!

**Comment by antonypro** [comment]
Hi, @biubiuKill!

I'm going to close this issue because the solution is present in version 2.4.3.
If you believe that are problems remaining, please ask to reopen this issue or open a new issue.

Thanks!
