### ISSUE TITLE
Call winId() cause cannot move window anymore

### ISSUE THREAD

**Issue by hcaihao** [antonypro/QGoodWindow#5]
```
MainWindow::MainWindow(QWidget* parent) : QGoodWindow(parent)
{
#ifdef QGOODWINDOW
    title_bar = new TitleBar(pixelRatio(), this);

    frame = new QFrame(this);
    qDebug() << frame->winId(); // Add this line

    m_frame_style = QString("QFrame {background-color: %0; border: %1;}");
```

Now, the window cannot move!

VS2019+QT5.15.2 x86

**Comment by antonypro** [comment]
@hcaihao:Thanks for the bug report, now I'm aware of that!

I don't found a solution for now, but now this is a priority.

**Comment by hcaihao** [comment]
I think this page can help you.

https://doc.qt.io/qt-5/qwidget.html

```
Native Widgets vs Alien Widgets
Introduced in Qt 4.4, alien widgets are widgets unknown to the windowing system. They do not have a native window handle associated with them. This feature significantly speeds up widget painting, resizing, and removes flicker.

Should you require the old behavior with native windows, you can choose one of the following options:

Use the QT_USE_NATIVE_WINDOWS=1 in your environment.
Set the Qt::AA_NativeWindows attribute on your application. All widgets will be native widgets.
Set the Qt::WA_NativeWindow attribute on widgets: The widget itself and all of its ancestors will become native (unless Qt::WA_DontCreateNativeAncestors is set).
Call QWidget::winId to enforce a native window (this implies 3).
Set the Qt::WA_PaintOnScreen attribute to enforce a native window (this implies 3).
```

**Comment by hcaihao** [comment]
If I set `QApplication::setAttribute(Qt::AA_NativeWindows)`, The window cannot move too.

**Comment by antonypro** [comment]
@hcaihao: I solved these problems, the next release will contain the solution.

Thank you for report!

**Comment by hcaihao** [comment]
That's wonderful!

**Comment by TTgogogo** [comment]
@antonypro when I call winId(), the window will not response. When will the next release come?

**Comment by antonypro** [comment]
@TTgogogo: This issue was fixed on version 1.1.

**Comment by antonypro** [comment]
@hcaihao: From my research, when you call `QWidget::winId()` or set `Qt::AA_NativeWindows`, the Qt attempts to change all alien widgets to native windows, in that case, the `WinWidget` lose the `WM_NCHITTEST` event.

To fix this this problem i installed a native event filter, and transferred all widgets `WM_NCHITTEST` events to the **QGoodWindow**, no matter you call `QWidget::winId()` or not.

**Comment by antonypro** [comment]
@hcaihao: Feel free to close this issue if you think it's solved, or report a possible related problem.

Thank you for report!

**Comment by antonypro** [comment]
Closing due inactivity.

**Comment by hcaihao** [comment]
Thank you, it works!
