### ISSUE TITLE
Always On Top not working

### ISSUE THREAD

**Issue by SpearVFX** [antonypro/QGoodWindow#50]
I'm trying to add always on top functionality in my application, but it seems that it isn't working. I know that the windowFlags are internally handled, but I tried to append the Qt::WindowStaysOnTop to all the initializations. It works if I remove anything related to FramelessWindow, but this beats the purpose, haha. Any ideas, or is it impossible?

**Comment by antonypro** [comment]
Hi, @SpearVFX!

This feature is planned for version 2.4.3.

You can see and test this feature on `QGoodWindow-2.4.3-beta3`:
https://github.com/antonypro/QGoodWindow/tree/test/QGoodWindow-2.4.3-beta3

Thanks!

**Comment by antonypro** [comment]
Hi, @SpearVFX!

I'm going to close this issue because the solution is present in version 2.4.3.
If you believe that are problems remaining, please ask to reopen this issue or open a new issue.

Thanks!
