### ISSUE TITLE
Examples runtime exception

### ISSUE THREAD

**Issue by hcaihao** [antonypro/QGoodWindow#53]
![Screenshot 2024-02-27 150104](https://github.com/antonypro/QGoodWindow/assets/3926845/230d3dde-3fa8-423f-8c19-4774adc623da)

![Screenshot 2024-02-27 150602](https://github.com/antonypro/QGoodWindow/assets/3926845/3575de74-848e-4722-8987-63cae949ba6f)

```
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Debug Error!

Program: C:\Qt\5.15.2\msvc2019\bin\ExampleMinimal.exe
Module: C:\Qt\5.15.2\msvc2019\bin\ExampleMinimal.exe
File: 

Run-Time Check Failure #0 - The value of ESP was not properly saved across a function call.  This is usually a result of calling a function declared with one calling convention with a function pointer declared with a different calling convention.

```

I use cmake generate vs2019 solution successful, but runtime exception after build.

env:
QT5.15.2+VS2019+Win11-- crash
QT5.15.12+VS2019+Win11-- crash
QT5.15.2 x64+VS2019+Win11 -- ok

**Comment by hcaihao** [comment]
I found this line cause the crash:

`pSetProcessDpiAwarenessContext(HANDLE(AWARENESS_CONTEXT_DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2));`

add "__stdcall" to func define solved

**Comment by antonypro** [comment]
@hcaihao:
 
As you also found, the reason of the crash is the missing calling convention in the following line:

https://github.com/antonypro/QGoodWindow/blob/abdeb9d57ab8ad8011547a1fb0621063a25640a2/QGoodWindow-2.4.4-beta1/QGoodWindow/src/qgoodwindow.cpp#L715

The version 2.4.4 beta 1 corrects this bug by adding the `WINAPI` to the function definition.
