### ISSUE TITLE
QGoodWindow conflicts with QTDesigner window 

### ISSUE THREAD

**Issue by hcaihao** [antonypro/QGoodWindow#54]
If I change an QTDesigner window' parent from qwidget to qgoodwindow, crash will happen.

```
AuthWindow::AuthWindow(QWidget* parent)
	: QWidget(parent) --> QGoodWindow
{
	ui.setupUi(this);
}

....

AuthWindow w;
w.show();
```

![Weixin Screenshot_20240228124738](https://github.com/antonypro/QGoodWindow/assets/3926845/b3c0970f-e99a-4e06-af74-40152c11fc85)

env: QT5.15.2(32)+VS2019+Win11

**Comment by antonypro** [comment]
@hcaihao:

If you want to use `FORMS` in your app, do not setup ui on `QGoodWindow`, instead, create helper(s) `QMainWindow` and setup ui on those windows, then convert the window to widget and use the new widget with `QGoodCentralWidget` or `QGoodWindow`.

Example already exists in `GoodShowCase`:

https://github.com/antonypro/QGoodWindow/blob/875ac7baf6512941c60d3363119e8b57a57bec26/QGoodWindow/Examples/GoodShowCase/GoodShowCase.pro#L40-L41

https://github.com/antonypro/QGoodWindow/blob/875ac7baf6512941c60d3363119e8b57a57bec26/QGoodWindow/Examples/GoodShowCase/mainwindow.h#L36-L51

https://github.com/antonypro/QGoodWindow/blob/875ac7baf6512941c60d3363119e8b57a57bec26/QGoodWindow/Examples/GoodShowCase/mainwindow.cpp#L42-L43

**Comment by hcaihao** [comment]
got it, tks
