### ISSUE TITLE
Cannot set title height and icon width.

### ISSUE THREAD

**Issue by hcaihao** [antonypro/QGoodWindow#55]
```
    QGoodWindow gw;
    QGoodCentralWidget gcw(&gw);
    gw.setCentralWidget(&gcw);
    gw.setWindowIcon(QIcon(R"logo.png"));
    gw.setTitleBarHeight(100);    -- gw.titleBarHeight() is 100, but the actual height is still 30
    gw.setIconWidth(100);  -- can't set icon width
    gw.show();
```

**Comment by antonypro** [comment]
Hi, @hcaihao!

The correct way to change the visual sizes mentioned is passing those values to the `QGoodCentralWidget` instance, passing to `QGoodWindow` only changes the mouse click behavior.

However, I've found problems on the version 2.4.4 beta 1 to set icon width, hence I published 2.4.4 beta 2 to fix these errors.

By using this fixed version you should be able to do advanced customization with easy.

See: https://github.com/antonypro/QGoodWindow/tree/test/QGoodWindow-2.4.4-beta2

Example:

```
#include <QGoodWindow>
#include <QGoodCentralWidget>

int main(int argc, char *argv[])
{
    QGoodWindow::setup();

    QApplication app(argc, argv);

    QGoodWindow gw;
    QGoodCentralWidget gcw(&gw);

    gcw.setIconWidth(60);
    gcw.setTitleBarHeight(60);
    gcw.setCaptionButtonWidth(60);

    gcw.setIconVisibility(QGoodCentralWidget::IconVisibilityType::IconOnLeftOfTitle);
    gcw.setTitleAlignment(Qt::AlignCenter);

    gcw.setLeftTitleBarWidget(new QPushButton(&gw));
    gcw.setRightTitleBarWidget(new QPushButton(&gw));
    gcw.setCenterTitleBarWidget(new QPushButton(&gw));

    gw.setCentralWidget(&gcw);

    gw.show();

    return app.exec();
}
```

**Comment by hcaihao** [comment]
good work, i'll try it.

**Comment by hcaihao** [comment]
Hi, I found 2 problems in 2.4.4 beta2.

```
    QGoodWindow gw;
    QGoodCentralWidget gcw(&gw);

    gcw.setIconWidth(60);   -- whatever value I set, icon width always 30
    gcw.setTitleBarHeight(60);
    gcw.setCaptionButtonWidth(60);

    gcw.setIconVisibility(QGoodCentralWidget::IconVisibilityType::IconOnLeftOfTitle);
    gcw.setTitleAlignment(Qt::AlignLeft);

    //gcw.setLeftTitleBarWidget(new QPushButton(&gw));
    //gcw.setRightTitleBarWidget(new QPushButton(&gw));
    //gcw.setCenterTitleBarWidget(new QPushButton(&gw));

    gw.setWindowIcon(QIcon(R"logo.png"));
    gw.setIconWidth(60);
    gw.setTitleBarHeight(10);    -- mouse click area is still 60
    gw.setCentralWidget(&gcw);
    gw.show();

```

**Comment by antonypro** [comment]
Hi, @hcaihao!

In order to make `setIconWidth` works as you expect, you need to use either `IconOnLeftOfWindow` or `IconHiddenAcceptMouseInput`, see [docs](https://github.com/antonypro/QGoodWindow/blob/master/docs/QGoodCentralWidget.md#enum-iconvisibilitytype) to see the difference.

`QGoodWindow` `setTitleBarHeight` won't work if called directly because it gets overridden by `QGoodCentralWidget` own calls to this function, so if you need to adjust title bar height when using `QGoodCentralWidget`, you should call the function of `QGoodCentralWidget`.

Also, if calling the `QGoodCentralWidget` function you don't need to call the `QGoodWindow` function too.

**Comment by hcaihao** [comment]
As you mentioned, I test this code, the icon width works, but cannot be showed.

```
    QGoodWindow gw;
    QGoodCentralWidget gcw(&gw);
    gcw.setIconWidth(60);
    gcw.setTitleBarHeight(60);
    gcw.setCaptionButtonWidth(60);
    gcw.setWindowIconText("Hello");  -- This two lines not work too.
    gcw.setTitleAlignment(Qt::AlignHCenter);
    gcw.setWindowIcon(QIcon("E:/logo.png"));
    gcw.setIconVisibility(QGoodCentralWidget::IconVisibilityType::IconOnLeftOfWindow);
    gcw.setIconVisibility(QGoodCentralWidget::IconVisibilityType::IconHiddenAcceptMouseInput);
    gw.setCentralWidget(&gcw);
    gw.show();
```


![image](https://github.com/antonypro/QGoodWindow/assets/3926845/75910f59-16c5-44ba-a5e2-4154ac50a781)

**Comment by antonypro** [comment]
@hcaihao:

The function `setWindowIconText` is not implemented and is [deprecated](https://doc.qt.io/qt-5/qwidget-obsolete.html#windowIconText-prop), so it will not work here.

To center the title, use `Qt::AlignCenter`, because alignment is always horizontal.

If you want the library to draw the icon for you, in Windows style, use only `QGoodCentralWidget::IconVisibilityType::IconOnLeftOfWindow`.

So you may have something like this:

```
QGoodWindow gw;
QGoodCentralWidget gcw(&gw);
gcw.setIconWidth(60);
gcw.setTitleBarHeight(60);
gcw.setCaptionButtonWidth(60);
gcw.setTitleAlignment(Qt::AlignCenter);
gcw.setIconVisibility(QGoodCentralWidget::IconVisibilityType::IconOnLeftOfWindow);
gw.setWindowIcon(QIcon(/*your icon*/));
gw.setCentralWidget(&gcw);
gw.show();
```

**Comment by hcaihao** [comment]
ok, the icon shows now, but still not fix the size i set.

![image](https://github.com/antonypro/QGoodWindow/assets/3926845/161aa8f9-0299-4f2c-8540-39102746d265)

**Comment by antonypro** [comment]
@hcaihao:

Looks good for me!

What you want to achieve that you're currently unable?

Size of which thing you means?

Could you please show the code that you're using?

**Comment by hcaihao** [comment]
I want to set the size of the icon to 60x60, but it still looks like 30x30.

```
int main(int argc, char *argv[])
{
    QGoodWindow::setup();

    QApplication app(argc, argv);

    QGoodWindow gw;
    QGoodCentralWidget gcw(&gw);
    gcw.setIconWidth(60);
    gcw.setTitleBarHeight(60);
    gcw.setCaptionButtonWidth(60);
    gcw.setTitleAlignment(Qt::AlignCenter);
    gcw.setIconVisibility(QGoodCentralWidget::IconVisibilityType::IconOnLeftOfWindow);
    gw.setWindowIcon(QIcon(R"(E:\logo.png)"));
    gw.setCentralWidget(&gcw);
    gw.show();

    return app.exec();
}
```

**Comment by antonypro** [comment]
@hcaihao:

Actually, the size of the icon and the title increases on high DPI environments only, however, you can fuse the title bar with the central widget, and hide the desired title bar items, like icon, tittle, and override them with yours custom items, this was done in [GoodShowCaseQML](https://github.com/antonypro/QGoodWindow/tree/master/QGoodWindow/Examples/GoodShowCaseQML) example, you will have more control of the window and is not mandatory to use QML to fuse title bar and central widget.

**Comment by hcaihao** [comment]
I see. Thank you.
