### ISSUE TITLE
Maybe memory leak in qgoodwindow

### ISSUE THREAD

**Issue by hcaihao** [antonypro/QGoodWindow#57]
![image](https://github.com/antonypro/QGoodWindow/assets/3926845/dddd388e-b977-4628-9771-7972da44f2e7)

**Comment by antonypro** [comment]
Hi, @hcaihao!

After you pointed me the memory leak, i found that `QGoodWindow` isn't releasing properly all of it's memory allocated objects.

Some changes were made on version 2.4.4 beta3 to fix this problem:

https://github.com/antonypro/QGoodWindow/blob/40cb47a3fb8ff24c648d826423f885cdfe929646/QGoodWindow-2.4.4-beta3/QGoodWindow/src/qgoodwindow.cpp#L557-L564
