### ISSUE TITLE
Blue border when window is focused.

### ISSUE THREAD

**Issue by sorudals** [antonypro/QGoodWindow#58]
![image](https://github.com/antonypro/QGoodWindow/assets/12227644/d3f0bfd6-a4b1-40a9-8a47-daade6d58350)

Hi AntonyPro,

Thank you for your good project.

I have a question regarding the border styling. Whenever I open a dialog or window, it displays a blue border that I cannot figure out how to remove.

Could you advise me on how to solve this issue?

**Comment by antonypro** [comment]
Hi, @Skm1221!

The border is part of the `QGoodCentralWidget` on Windows and Linux, and on Windows 11 it uses native APIs to change the border color, you cannot remove it, however, you could change the border color anytime with the function [QGoodCentralWidget::setActiveBorderColor(const QColor & color)](https://github.com/antonypro/QGoodWindow/blob/master/docs/QGoodCentralWidget.md#slot-public-void-setactivebordercolorconst-qcolor--color).

Thanks!

**Comment by sorudals** [comment]
Thanks! 

It's resolved, I'll close this issue

Thank you for your help :)
