### ISSUE TITLE
Titlebar buttons width problem

### ISSUE THREAD

**Issue by 956MB** [antonypro/QGoodWindow#6]
Hi there. First, this project is great, really helpful, it's been just what I needed, but I have this little annoying thing happening.

All I'm trying to do is change the window control button widths from 36 to 46, but when I do, it's like the area the titlebar detects for hovering over the control buttons doesn't change. So the minimize button at 46 width is bugged:

```c++
    minbtn = new CaptionButton(CaptionButton::IconType::Minimize, pixel_ratio, this);
    minbtn->setFixedSize(qRound(36 * pixel_ratio), qRound(29 * pixel_ratio));
    restorebtn = new CaptionButton(CaptionButton::IconType::Restore, pixel_ratio, this);
    restorebtn->setFixedSize(qRound(36 * pixel_ratio), qRound(29 * pixel_ratio));
    maxbtn = new CaptionButton(CaptionButton::IconType::Maximize, pixel_ratio, this);
    maxbtn->setFixedSize(qRound(36 * pixel_ratio), qRound(29 * pixel_ratio));
    clsbtn = new CaptionButton(CaptionButton::IconType::Close, pixel_ratio, this);
    clsbtn->setFixedSize(qRound(36 * pixel_ratio), qRound(29 * pixel_ratio));
```
![normal](https://user-images.githubusercontent.com/39519792/146446378-3d990c19-f902-4603-ae8a-98377903216a.gif)

to
```c++
    minbtn = new CaptionButton(CaptionButton::IconType::Minimize, pixel_ratio, this);
    minbtn->setFixedSize(qRound(46 * pixel_ratio), qRound(29 * pixel_ratio));
    restorebtn = new CaptionButton(CaptionButton::IconType::Restore, pixel_ratio, this);
    restorebtn->setFixedSize(qRound(46 * pixel_ratio), qRound(29 * pixel_ratio));
    maxbtn = new CaptionButton(CaptionButton::IconType::Maximize, pixel_ratio, this);
    maxbtn->setFixedSize(qRound(46 * pixel_ratio), qRound(29 * pixel_ratio));
    clsbtn = new CaptionButton(CaptionButton::IconType::Close, pixel_ratio, this);
    clsbtn->setFixedSize(qRound(46 * pixel_ratio), qRound(29 * pixel_ratio));
```
![bugged](https://user-images.githubusercontent.com/39519792/146446385-c79f2fbd-6d1f-48d7-bf03-db84403ce759.gif)

I've changed nothing else about the QGoodWindow source.  Making a different class myself for the buttons to replicate them is easy enough, but I'm just confused and curious why this happens with your code.

**Comment by antonypro** [comment]
Hi @956MB, firstly thank you for saying that this project is great! :)

About your issue, please note that this library doesn’t attempt to deduce the margins from your project (title bar height, icon width and left\right margins widths). It’s done that way to give for who uses this library maximum flexibility to define exactly the area for move and maximize the window and the area of your custom buttons, it could be a `QML` widget, `WebEngine` site etc. The examples provided uses only rectangular `QWidget`s but if you have buttons with rounded corners, or smaller than the size of the whole margin itself, you can apply a mask to fit to it, more details on the `README` of this project.

In short I think you need to increase the right margin width to fit the width of yours buttons, calling:
              
	setMargins(qRound(30 * pixelRatio()), qRound(30 * pixelRatio()), 0,
	/*Right Margin Width ->*/ qRound(46 * 3 * pixelRatio()));

Here: https://github.com/antonypro/QGoodWindow/blob/1bb87bf65198b419cd6212e693c8278c7633c973/QGoodWindow/Examples/GoodShowCase/mainwindow.cpp#L185

If you don’t want to manually change the width each time, you can query the current width of all buttons summed and call `setMargins` with this value to reflect each change to the title bar, for example going in and out of full screen mode, setting 0 to right margin on full screen and _“my_buttons->width()”_ when going back.

That being said I don’t think it’s actually a bug with the code provided, you just need to inform the  changed width of the buttons to the library.

**Comment by 956MB** [comment]
@antonypro Yeah, I knew it wasn't a bug or anything, it's always just me missing something or not paying enough attention. Thank you.
