### ISSUE TITLE
syntax error: identifier 'qgoodintptr'

### ISSUE THREAD

**Issue by PaddleStroke** [antonypro/QGoodWindow#60]
`    bool nativeEvent(const QByteArray &eventType, void *message, qgoodintptr *result) override;`

Is giving a 

> Error	C2061	syntax error: identifier 'qgoodintptr'

Commenting out this function and it now builds

**Comment by antonypro** [comment]
@PaddleStroke:

The `qgoodintptr` is defined in [intcommon.h](https://github.com/antonypro/QGoodWindow/blob/875ac7baf6512941c60d3363119e8b57a57bec26/QGoodWindow/QGoodWindow/src/intcommon.h).

It exists to allow the same source code to be portable among Qt5 and Qt6, as you can see in the source code.

Thanks!

**Comment by PaddleStroke** [comment]
Thanks for your feedback. It appears that doing a ctrl-F search on visual studio did not searched this file. So I think VS was perhaps not including all the files correctly. I'll need to look into it again.
